// Writes COVERAGE.md next to this file from the raw cache only. Never fetches.
//
//   HOOPS_DATA_DIR=... npx tsx packages/data/src/nba/coverage.ts
//
// Every number comes from a cached response written by fetchAll.ts. Failure reasons come from
// the fetchAll run summary. Columns that are null for a whole season are listed so downstream
// code knows which fields are missing in early years.

process.env.HOOPS_OFFLINE = '1'

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Row } from './client.ts'
import { seasonId } from './client.ts'
import {
  FIRST_SEASON,
  fetchAllPlayers,
  fetchDraftHistory,
  fetchGameLog,
  fetchPlayerAdvanced,
  fetchPlayerBio,
  fetchPlayerPer100,
  fetchPlayerTotals,
  fetchStandings,
  fetchTeamAdvanced,
  fetchTeamIds,
  fetchTeamRoster,
  fetchTeamTotals,
  LAST_SEASON,
} from './endpoints.ts'
import { type Failure, type RunSummary, SUMMARY_PATH } from './fetchAll.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
export const COVERAGE_PATH = path.join(here, 'COVERAGE.md')

/** Column order of the per-season table. */
const COLS: [string, (y: number) => Promise<Row[]>][] = [
  ['bio', fetchPlayerBio],
  ['per100', fetchPlayerPer100],
  ['totals', (y) => fetchPlayerTotals(y)],
  ['adv', fetchPlayerAdvanced],
  ['totals_po', (y) => fetchPlayerTotals(y, 'Playoffs')],
  ['team_tot', (y) => fetchTeamTotals(y)],
  ['team_adv', fetchTeamAdvanced],
  ['team_po', (y) => fetchTeamTotals(y, 'Playoffs')],
  ['standings', fetchStandings],
  ['tg_rs', (y) => fetchGameLog(y, 'T', 'Regular Season')],
  ['tg_po', (y) => fetchGameLog(y, 'T', 'Playoffs')],
  ['tg_pi', (y) => fetchGameLog(y, 'T', 'PlayIn')],
  ['pg_rs', (y) => fetchGameLog(y, 'P', 'Regular Season')],
  ['pg_po', (y) => fetchGameLog(y, 'P', 'Playoffs')],
]

/** Endpoints audited for all-null columns. Rank columns are skipped. */
const AUDIT: [string, (y: number) => Promise<Row[]>][] = [
  ['bio', fetchPlayerBio],
  ['per100', fetchPlayerPer100],
  ['adv', fetchPlayerAdvanced],
  ['team_adv', fetchTeamAdvanced],
  ['standings', fetchStandings],
  ['tg_rs', (y) => fetchGameLog(y, 'T', 'Regular Season')],
  ['pg_rs', (y) => fetchGameLog(y, 'P', 'Regular Season')],
  ['rosters', allRosters],
]

/** Every team's roster rows for a season, concatenated. */
async function allRosters(y: number): Promise<Row[]> {
  const out: Row[] = []
  for (const id of await fetchTeamIds(y)) out.push(...(await fetchTeamRoster(y, id)))
  return out
}

/** Notes written after reading the audit. Kept here so a re-run reproduces the file. */
const NOTES: string[] = [
  'leaguedash* endpoints list a traded player once, under his final team, with summed stats. Per-game team membership comes from leaguegamelog P.',
  'leaguegamelog with Counter=1000 does not truncate: 1997-98 P Regular Season returns 24,001 rows in one response.',
  'leaguegamelog SeasonType=PlayIn returns HTTP 200 with 0 rows before 2019-20. 2019-20 has the 2-row bubble play-in (POR vs MEM).',
  'commonteamroster is a season-end snapshot, not everyone who appeared: per season 100-150 player-team pairs exist only in leaguegamelog P (traded or cut mid-season). 2002-03 is odd: 467 rows, 79 of them players with no game for that team.',
  'commonallplayers needs a Season param even with IsOnlyCurrentSeason=0; it is sent as 2025-26.',
  'drafthistory SEASON is a string draft year (e.g. "1997"), not a season id.',
  'commonteamroster HOW_ACQUIRED is null for every row through 2008-09 and populated from 2009-10.',
  'leaguestandingsv3 before 2000-01 has null ClinchIndicator, LeagueRank, L10, streak and clinch fields. Every season has null LeagueGamesBack, PlayoffSeeding, ClinchedPostSeason, NEUTRAL through 2022-23, plus months with no games. WINS, LOSSES, records and PointsPG are always filled.',
]

interface Cell {
  n: number | null
  note: string
}

async function count(fn: () => Promise<Row[]>): Promise<Cell> {
  try {
    return { n: (await fn()).length, note: '' }
  } catch (e) {
    return { n: null, note: (e instanceof Error ? e.message : String(e)).slice(0, 120) }
  }
}

function loadSummary(): RunSummary | null {
  if (!existsSync(SUMMARY_PATH)) return null
  return JSON.parse(readFileSync(SUMMARY_PATH, 'utf8')) as RunSummary
}

function allNullColumns(rows: Row[]): string[] {
  if (rows.length === 0) return []
  const keys = Object.keys(rows[0] ?? {}).filter((k) => !k.endsWith('_RANK'))
  return keys.filter((k) => rows.every((r) => r[k] === null || r[k] === ''))
}

export async function buildCoverage(): Promise<string> {
  const summary = loadSummary()
  const failures: Failure[] = summary?.failures ?? []
  const lines: string[] = []
  lines.push('# stats.nba.com coverage')
  lines.push('')
  lines.push(
    `Generated by coverage.ts from the raw cache. fetchAll run: ${summary?.ranAt ?? 'none'}.`,
  )
  lines.push('Row counts per season. `-` means not cached (see failures below).')
  lines.push('')
  const once = {
    draft: await count(fetchDraftHistory),
    all_players: await count(fetchAllPlayers),
  }
  lines.push('## Once')
  lines.push('')
  lines.push('| endpoint | rows |')
  lines.push('|---|---|')
  lines.push(`| drafthistory (all years) | ${once.draft.n ?? '-'} |`)
  lines.push(`| commonallplayers (IsOnlyCurrentSeason=0) | ${once.all_players.n ?? '-'} |`)
  lines.push('')
  lines.push('## Per season')
  lines.push('')
  lines.push(`| season | ${COLS.map(([c]) => c).join(' | ')} | rosters |`)
  lines.push(`|---|${COLS.map(() => '---:').join('|')}|---|`)
  const empties: string[] = []
  const notCached: string[] = []
  const nullCols: string[] = []
  for (let y = FIRST_SEASON; y <= LAST_SEASON; y++) {
    const season = seasonId(y)
    const cells: string[] = []
    for (const [name, fn] of COLS) {
      const c = await count(() => fn(y))
      cells.push(c.n === null ? '-' : String(c.n))
      if (c.n === null) notCached.push(`${season} ${name}: ${c.note}`)
      if (c.n === 0) empties.push(`${season} ${name}: 200 with 0 rows`)
    }
    let rosterTeams = 0
    let rosterRows = 0
    let teamCount = 0
    try {
      const ids = await fetchTeamIds(y)
      teamCount = ids.length
      for (const id of ids) {
        const c = await count(() => fetchTeamRoster(y, id))
        if (c.n === null) notCached.push(`${season} roster ${id}: ${c.note}`)
        else {
          rosterTeams++
          rosterRows += c.n
          if (c.n === 0) empties.push(`${season} roster ${id}: 200 with 0 rows`)
        }
      }
    } catch (e) {
      notCached.push(`${season} team ids: ${(e as Error).message.slice(0, 120)}`)
    }
    cells.push(`${rosterTeams}/${teamCount} teams, ${rosterRows} rows`)
    lines.push(`| ${season} | ${cells.join(' | ')} |`)
    for (const [name, fn] of AUDIT) {
      try {
        const cols = allNullColumns(await fn(y))
        if (cols.length) nullCols.push(`| ${season} | ${name} | ${cols.join(', ')} |`)
      } catch {
        // not cached; already listed
      }
    }
  }
  lines.push('')
  lines.push('## Failed requests')
  lines.push('')
  if (failures.length === 0 && notCached.length === 0) lines.push('None.')
  for (const f of failures) lines.push(`- ${f.season} ${f.job}: ${f.reason}`)
  for (const s of notCached) lines.push(`- not cached: ${s}`)
  lines.push('')
  lines.push('## Empty responses (HTTP 200, 0 rows)')
  lines.push('')
  if (empties.length === 0) lines.push('None.')
  for (const s of empties) lines.push(`- ${s}`)
  lines.push('')
  lines.push('## Columns null for a whole season')
  lines.push('')
  if (nullCols.length === 0) lines.push('None.')
  else {
    lines.push('| season | endpoint | columns |')
    lines.push('|---|---|---|')
    lines.push(...nullCols)
  }
  lines.push('')
  lines.push('## Notes')
  lines.push('')
  for (const n of NOTES) lines.push(`- ${n}`)
  lines.push('')
  return lines.join('\n')
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  buildCoverage()
    .then((md) => {
      writeFileSync(COVERAGE_PATH, md)
      console.log(`wrote ${COVERAGE_PATH}`)
    })
    .catch((e) => {
      console.error(e)
      process.exit(1)
    })
}
