// Generates COVERAGE.md: per-season row counts for every loaded table, latest seasons,
// salary coverage per season, and the known gaps. Every number comes from the cached data.
// Run: HOOPS_DATA_DIR=... npx tsx packages/data/src/open/coverage.ts > packages/data/src/open/COVERAGE.md

import {
  awardWinners,
  latestSeason,
  loadAllStarSelections,
  loadAwardShares,
  loadEndOfSeasonTeams,
  loadEndOfSeasonVoting,
} from './awards.ts'
import * as b from './bref.ts'
import { loadCapHistory } from './cap.ts'
import { toSalaryLines } from './contracts.ts'
import { loadCurrentContracts } from './contracts-current.ts'
import { loadPlayerSalaries, loadWaybackSalaries, matchPlayerIds } from './salaries.ts'
import { findSnapshot, loadWaybackContracts } from './wayback.ts'

const SEASONS = Array.from({ length: 29 }, (_, i) => 1998 + i)

function countBy<T>(rows: T[], key: (r: T) => number): Map<number, number> {
  const m = new Map<number, number>()
  for (const r of rows) key(r) !== undefined && m.set(key(r), (m.get(key(r)) ?? 0) + 1)
  return m
}

function table(header: string[], rows: (string | number)[][]): string {
  const line = (cells: (string | number)[]) => `| ${cells.join(' | ')} |`
  return [line(header), line(header.map(() => '---')), ...rows.map(line)].join('\n')
}

function pct(n: number, d: number): string {
  return d === 0 ? '-' : `${((100 * n) / d).toFixed(1)}%`
}

async function main(): Promise<void> {
  const out: string[] = []
  const p = (s = '') => out.push(s)

  p('# Open-data coverage, seasons 1998..2026')
  p()
  p('Generated by `packages/data/src/open/coverage.ts` from the cached raw files.')
  p('season = year the season ends (1998 = 1997-98). All tables filtered to lg = NBA.')
  p()

  // ---- player-season tables
  const adv = b.loadAdvanced()
  const per100 = b.loadPer100()
  const per36 = b.loadPer36()
  const perGame = b.loadPerGame()
  const totals = b.loadTotals()
  const stints = b.totalsStints(totals)
  const pbp = b.loadPlayByPlay()
  const shooting = b.loadShooting()
  const info = b.loadSeasonInfo()
  const playerTables: [string, { season: number }[]][] = [
    ['Advanced', adv],
    ['Per 100', per100],
    ['Per 36', per36],
    ['Per Game', perGame],
    ['Totals (all rows)', totals],
    ['Totals (stints)', stints],
    ['Play By Play', pbp],
    ['Shooting', shooting],
    ['Season Info', info],
  ]
  const players = countBy(
    [...new Set(stints.map((r) => `${r.season}|${r.player_id}`))].map((k) => ({
      season: Number(k.split('|')[0]),
    })),
    (r) => r.season,
  )
  p('## Player-season tables (sumitrodatta/bball-reference-datasets)')
  p()
  p('Rows per season. "players" = distinct player_id with a stint row in Player Totals.')
  p()
  p(
    table(
      ['season', ...playerTables.map(([n]) => n), 'players'],
      SEASONS.map((s) => [
        s,
        ...playerTables.map(([, rows]) => countBy(rows, (r) => r.season).get(s) ?? 0),
        players.get(s) ?? 0,
      ]),
    ),
  )
  p()
  p(`Latest season: ${playerTables.map(([n, rows]) => `${n} ${latestSeason(rows)}`).join(', ')}.`)
  p(`Career Info rows overlapping 1998..2026: ${b.loadCareerInfo().length}.`)
  p()

  // ---- team tables
  const teamTables: [string, { season: number; abbreviation: string | null }[]][] = [
    ['Team Abbrev', b.loadTeamAbbrev()],
    ['Team Summaries', b.loadTeamSummaries()],
    ['Team Totals', b.loadTeamTotals()],
    ['Team Per Game', b.loadTeamPerGame()],
    ['Team Per 100', b.loadTeamPer100()],
    ['Opp Totals', b.loadOppTotals()],
    ['Opp Per 100', b.loadOppPer100()],
  ]
  p('## Team tables')
  p()
  p(
    'Rows per season including the League Average row where the file has one (abbreviation = null).',
  )
  p()
  p(
    table(
      ['season', ...teamTables.map(([n]) => n), 'teams'],
      SEASONS.map((s) => [
        s,
        ...teamTables.map(([, rows]) => countBy(rows, (r) => r.season).get(s) ?? 0),
        (teamTables[0] as [string, { season: number }[]])[1].filter((r) => r.season === s).length,
      ]),
    ),
  )
  p()
  p(`Latest season: ${teamTables.map(([n, rows]) => `${n} ${latestSeason(rows)}`).join(', ')}.`)
  p()

  // ---- draft
  const draft = b.loadDraft({ from: 1997 })
  p('## Draft (Draft Pick History)')
  p()
  p('season = draft year. The 1997 draft is the rookie class of 1997-98.')
  p()
  const draftBy = countBy(draft, (r) => r.season)
  p(
    table(
      ['draft', 'picks', 'with player_id', 'with overall_pick'],
      [1997, ...SEASONS].map((s) => [
        s,
        draftBy.get(s) ?? 0,
        draft.filter((r) => r.season === s && r.player_id).length,
        draft.filter((r) => r.season === s && r.overall_pick !== null).length,
      ]),
    ),
  )
  p()
  p(`Latest draft: ${latestSeason(draft)}.`)
  p()

  // ---- awards
  const shares = loadAwardShares()
  const eos = loadEndOfSeasonTeams()
  const voting = loadEndOfSeasonVoting()
  const allStar = loadAllStarSelections()
  p('## Awards')
  p()
  p(
    table(
      [
        'season',
        'award votes',
        'winners',
        'awards',
        'EoS team slots',
        'EoS voting rows',
        'All-Stars',
      ],
      SEASONS.map((s) => {
        const sh = shares.filter((r) => r.season === s)
        return [
          s,
          sh.length,
          awardWinners(sh).length,
          [...new Set(sh.map((r) => r.award))].map((a) => a.slice(4)).join(' '),
          eos.filter((r) => r.season === s).length,
          voting.filter((r) => r.season === s).length,
          allStar.filter((r) => r.season === s).length,
        ]
      }),
    ),
  )
  p()
  p(
    `Latest season: Award Shares ${latestSeason(shares)}, End of Season Teams ${latestSeason(eos)}, ` +
      `End of Season Teams (Voting) ${latestSeason(voting)}, All-Star Selections ${latestSeason(allStar)}.`,
  )
  p()

  // ---- salaries
  const csvSal = matchPlayerIds(loadPlayerSalaries({ from: 1998, to: 2020 }), info)
  const wbSal = await loadWaybackSalaries()
  const all = [...csvSal, ...wbSal]
  const infoIds = new Map<number, Set<string>>()
  for (const r of info) {
    const set = infoIds.get(r.season) ?? new Set()
    set.add(r.player_id)
    infoIds.set(r.season, set)
  }
  p('## Salaries')
  p()
  p('1998..2020: sumitrodatta/nba-player-salaries `Player Salaries.csv` (names + team, no ids).')
  p(
    'Ids matched to Player Season Info by season + team + normalized name (fallback: unique name in season).',
  )
  p(
    '2021..2026: Wayback Machine snapshot of basketball-reference.com/contracts/players.html nearest opening night.',
  )
  p('The `y1` column of that snapshot is the season salary; ids come from `data-append-csv`.')
  p()
  p('"covered" = share of players with a Player Totals stint that season who have a salary row.')
  p('"extra" = salary rows whose player_id has no stint that season (on contract, never played).')
  p()
  const salRows: (string | number)[][] = []
  for (const s of SEASONS) {
    const rows = all.filter((r) => r.season_end === s)
    const ids = new Set(rows.map((r) => r.player_id).filter((x): x is string => x !== null))
    const played = infoIds.get(s) ?? new Set<string>()
    const covered = [...played].filter((id) => ids.has(id)).length
    const extra = [...ids].filter((id) => !played.has(id)).length
    const src = rows[0]?.source ?? '-'
    const snap = src === 'wayback' ? ((await findSnapshot(s))?.timestamp ?? '-') : '-'
    salRows.push([
      s,
      src,
      rows.length,
      rows.filter((r) => r.player_id).length,
      pct(rows.filter((r) => r.player_id).length, rows.length),
      played.size,
      covered,
      pct(covered, played.size),
      extra,
      rows.filter((r) => r.option).length,
      snap,
    ])
  }
  p(
    table(
      [
        'season',
        'source',
        'rows',
        'with id',
        'id rate',
        'players',
        'covered',
        'covered %',
        'extra',
        'options',
        'snapshot',
      ],
      salRows,
    ),
  )
  p()
  const csvLatest = latestSeason(
    loadPlayerSalaries({ from: 1985, to: 2100 }).map((r) => ({ season: r.season })),
  )
  p(
    `Player Salaries.csv latest season: ${csvLatest}. Wayback seasons: ${[...new Set(wbSal.map((r) => r.season_end))].join(', ')}.`,
  )
  p()

  // ---- forward view
  const cur = loadCurrentContracts()
  const curLines = toSalaryLines(cur)
  p('## Forward view (current contracts page, fetched 2026-09-10)')
  p()
  p(
    `First salary column: ${cur.columns.y1} (season_end ${cur.first_season_end}). Rows: ${cur.rows.length}, all with player_id: ${cur.rows.every((r) => r.player_id)}.`,
  )
  p()
  p(
    table(
      ['season', 'salary rows', 'player options', 'team options'],
      Object.values(cur.columns)
        .map((label) => Number(label.slice(0, 4)) + 1)
        .map((s) => [
          s,
          curLines.filter((l) => l.season_end === s).length,
          curLines.filter((l) => l.season_end === s && l.option === 'player').length,
          curLines.filter((l) => l.season_end === s && l.option === 'team').length,
        ]),
    ),
  )
  p()
  p(
    'Each Wayback snapshot carries the same forward view as of that opening night (y1..y6 with option flags).',
  )
  const wbForward: (string | number)[][] = []
  for (const s of [2021, 2022, 2023, 2024, 2025, 2026]) {
    const page = await loadWaybackContracts(s)
    if (!page) continue
    const lines = toSalaryLines(page)
    wbForward.push([
      s,
      page.snapshot.timestamp,
      page.columns.y1 ?? '',
      page.rows.length,
      Object.values(page.columns)
        .map((label) => Number(label.slice(0, 4)) + 1)
        .map((y) => lines.filter((l) => l.season_end === y).length)
        .join(' / '),
      lines.filter((l) => l.option === 'player').length,
      lines.filter((l) => l.option === 'team').length,
    ])
  }
  p()
  p(
    table(
      ['season', 'snapshot', 'y1', 'rows', 'rows per y1..y6', 'player options', 'team options'],
      wbForward,
    ),
  )
  p()

  // ---- cap
  const cap = loadCapHistory()
  p('## Salary cap (basketball-reference salary-cap-history, cached)')
  p()
  p(
    `Seasons 1998..2026 present: ${cap.length} of 29. 1998 = $${cap[0]?.cap.toLocaleString('en-US')}, 2026 = $${cap.at(-1)?.cap.toLocaleString('en-US')}.`,
  )
  p(`Full page covers ${loadCapHistory(1985, 2027).length} seasons, 1985..2027.`)
  p()

  // ---- gaps
  const csvNoId = csvSal.filter((r) => !r.player_id).length
  p('## Gaps')
  p()
  p(
    `- Salaries 1998..2020 have no player ids in the source; ${csvNoId} of ${csvSal.length} rows stay unmatched after name matching. Those need the id_map override file. "extra" is 0 for csv rows by construction (ids only come from stints).`,
  )
  const s2014 = csvSal.filter((r) => r.season_end === 2014).length
  p(
    `- Salaries 2014 are short in the source: ${s2014} rows vs 450+ in neighbouring seasons. One NA-salary row (1998+) is dropped.`,
  )
  p(
    '- Salaries 2021..2026 come from the bref contracts page, which lists standard contracts only: two-way, Exhibit 10 and 10-day deals are absent. See "covered %" above for how many players with minutes are missing.',
  )
  p(
    '- The 2025 snapshot (2024-10-07) is 15 days before opening night; the next one (2024-11-15) is 24 days after. Nearest was chosen.',
  )
  p(
    `- Contract length and options before 2021 are not in any free source; only 2021+ snapshots carry option flags. The current page gives ${cur.first_season_end - 1}-${String(cur.first_season_end).slice(2)} onward.`,
  )
  p(
    `- Award Shares and End of Season Teams stop at ${latestSeason(shares)}; the 2026 awards were not in the repo at its 2026-04-13 update. All-Star Selections has ${latestSeason(allStar)}.`,
  )
  p(
    `- Draft Pick History stops at the ${latestSeason(draft)} draft; the 2026 draft is missing for the same reason.`,
  )
  p(
    '- Team Per 100 and Opp Per 100 have no League Average row (29/30 rows per season vs 30/31 in the other team files).',
  )
  p('- Player Play By Play and Player Shooting start in 1997 in the source, so 1998+ is complete.')
  p(
    '- Luxury tax, aprons, min/max salary and rookie scale are not in these files. Hand-curated era table is a separate lane.',
  )
  console.log(out.join('\n'))
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
